### ISSUE TITLE
being able to force/ask user to update app

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#226]
## Context/goal: 
- [ ] make route or something else to set min version of android/iOS (show force update)
- [ ] make design for telling user to update app
- [ ] implement feature in Me

play core has a in app updates features:
https://developer.android.com/guide/playcore/in-app-updates
@danieltcacenco could you look for a iOS version of in-app-updates

## Task

1. non-intrusive -> 'snackbar' notification; this is a notification which shows on voucher page when people open the app but does not need user feedback (user can just use the app without intrusion) -> is shown on all updates
2. intrusive - > Popup modal with a question "there is an important update, please update yes/no"/"Er is een belangrijke nieuwe update, wilt u deze installeren? Ja / nee" only with important updates -> We should be able to turn this on/off depending on the release. For example each major app release this will be enforced
3. complete block -> Security breach, legacy api routes that are fased out. With this feature the user can't access their voucher or scanner without updating.

**Comment by jamalv** [comment]
this feature should only be used as an absolute last resort. it is very bad ux.

**Comment by jknnr** [comment]
lets not force but make a notification

**Comment by maxvisser** [comment]
Having this option would ofcourse only be used for security purposes. If we find some gamebreaking security flaw we can block unsupported apps.

**Comment by danieltcacenco** [comment]
Yes sure, is possible to check if app have new version on app store and we can show to user an alert with this information.
Second, obvious in future can appear some needed to force user to update, many different apps are doing the same and its normal process for that.

**Comment by maxvisser** [comment]
@dev-rminds We had a call about this issue. App needs to be able to fetch the minimum app version from the backend (to check and force user to update).

**Comment by jamalv** [comment]
we should never use this as part of a regulair update proces, only in very extreme security related situations, otherwise it can be used for depreciating old versions after allowing for a grace period, preferrably of many months, so that only a very small number of users will be confronted with this.

(if a user wants to use the app to scan a voucher and there is a long cue in the store, it would be very poor if they need to wait for an update)

**Comment by maxvisser** [comment]
ofcourse this is clear now ;) as we will implement minimum version to backend; We will first use it after a month from now to get rid of the old api endpoints

**Comment by maxvisser** [comment]
- Snackbar for update app (non-intrusive popup to show to user that there is a new version of the app)
- Intrusive force user to update
  - needs a backend feature which tells the apps version is lower then minimum required version.

**Comment by maxvisser** [comment]
On iOS we could do a static message on profile page which can be dismissed.

**Comment by danieltcacenco** [comment]
done

**Comment by danieltcacenco** [comment]
change redesign snakbar, change logic of updatenotifier class, add close button and rethink logic of appear.

**Comment by jknnr** [comment]
done
