### ISSUE TITLE
Epic. Signup-flow. Requester - Only Peer2Peer validations

### ISSUE THREAD

**Issue by danrminds** [teamforus/me#336]
## Context/goal: 
- [x] You can not send the record to the validation dashboard (no possibility to choose who validates).
- [x] Possible to show the QR-Code for Peer2Peer validation
- [x] When scanning a Peer2Peer validation - show the screen to select which organisation you want to validate it for (should be the same now)
