### ISSUE TITLE
Epic. Signup-flow. Requester - View of records

### ISSUE THREAD

**Issue by danrminds** [teamforus/me#337]
## Context/goal: 
- [x] You can view record list and view a separate record
- [x] In the list of records you can see the `Record type` and `Record value` and number of validations (if validated). 
- [x] View of a separate record - see what validations you already have (identity public key who validated and organisation - if applicable)
