### ISSUE TITLE
Epic. Signup-flow. Requester - MeApp overview.

### ISSUE THREAD

**Issue by danrminds** [teamforus/me#338]
## Context/goal: 
To implement the requirements for the new milestone - we have to adapt what we have already in the Me App on the part of records and validations.

- [x] You should be able to view the records list and view a separate record #337
- [x] In the list of records you can see the `Record type` and `Record value` and number of validations (if validated). #337
- [x] View of a separate record - see what validations you already have (identity public key who validated and organisation - if applicable) #337
- [x] You should not be able to add new records #335 
- [x] You should not be able to send the record to the validation dashboard (no possibility to choose who validates). #336
- [x] Possible to show the QR-Code for Peer2Peer validation #336
- [x] When scanning a Peer2Peer validation - show the screen to select which organisation you want to validate it for  #336
