### ISSUE TITLE
Epic. Signup-flow. Requester - Record view

### ISSUE THREAD

**Issue by danrminds** [teamforus/me#340]
## Context/goal: 
![Screenshot 2019-10-07 16 49 38](https://user-images.githubusercontent.com/33207036/66322689-cc76ac00-e922-11e9-8a53-d1ba0e23f482.png)

- [x] Rename "Validators" to "Validations"
- [x] Replace the subtitle of each validation with the date and time stamp
- [x] Remove (or not) the icons on the right side
- [x] A new type - when instead of an organisation name - you see the public key `0x4j54j3kj56h34v3256n565432c` (show only how much you have space and follow it by "..."), and a different generic icon instead of the logo.

**Comment by Myshelova** [comment]
"A new type - when instead of an organisation name - you see the public key 0x4j54j3kj56h34v3256n565432c (show only how much you have space and follow it by "..."), and a different generic icon instead of the logo."
– is this for non-organisation validations? from 'personal profiles' of people

**Comment by jamalv** [comment]
Yes, it is for personal profiles. Regarding your question if we want to show public key or some other info; maybe it indeed is a good idea to either show the email address or a username. 

Currently we only have email addresses in the system, but I like the idea of the username a lot.

**Comment by Myshelova** [comment]
https://zpl.io/V490MYQ
+ will make a design for another screen resolution

**Comment by Myshelova** [comment]
Android: https://zpl.io/adYP90E https://zpl.io/aMj95A7
iOS: https://zpl.io/V490MYQ
