### ISSUE TITLE
iOS: Test transaction fixes

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#389]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/73340019-37554580-427a-11ea-814e-fa8d0da18c13.png)

## Tasks

- [ ] reproduce token is not valid issue

- [ ] Header should clearly state 'Test betalingsverzoek'

- [ ] NOT 2 DAGEN GELDIG VALID -> should be '+1 Gemeente'

- [ ] DenyK -> should be the organization of user (if its there) or hardcode NL: '+1 Organisatie' EN: '+1 Organization'

- [ ] check if confirmation popup should state 'Bevestig testbetaling'

**Comment by maxvisser** [comment]
How to reproduce:

got to dev.westerkwartier.forus.io/provider/#!/sign-up

use me-app to login on second step

create organization using test KVK
One of these numbers:

Row 1 | Row 2 | Row 3
-- | -- | --
69599084 - Eenmanszaak | 69599068 - Stichting | 90001966 - Onderlinge Waarborg Maatschappij
90004841 - Eenmanszaak | 90000102 - Stichting | 90003179 - Vereniging
68727720 - NV | 69599076 - VoF | 90000749 - Vereniging van Eigenaars
90004760 - NV | 90005368 - VoF | 90001745 - Maatschap
68750110 - BV | 90002636 - Coöperatie | 90003942 - Commanditaire Vennootschap
90001354 - BV | 90001532 - Kerkgenootschap | 90002148 - Overige Privaatrechtelijke Rechtspersoon
