### ISSUE TITLE
Hide voucher qr and buttons on expired vouchers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#434]
## Task

- [ ] hide qr code from expired voucher
- [ ] remove sent voucher to mail button from expired voucher
- [ ] remove voucher info button from expired voucher 

I think we could show fund image instead of qr code

**Comment by maxvisser** [comment]
Not sure if this is aswell applicable for iOS

**Comment by jknnr** [comment]
@maestrovsmaster let's try to implement this, the logo is here: https://media.forus.io/assets/me-logo.png

**Comment by danieltcacenco** [comment]
Done:
hide qr code from expired voucher in MVoucherViewController and MProductVoucherViewController
remove sent voucher to mail button from expired voucher  in MVoucherViewController and MProductVoucherViewController
remove voucher info button from expired voucher  in MVoucherViewController and MProductVoucherViewController

**Comment by jknnr** [comment]
done
