### ISSUE TITLE
Error handling: Check all errors for specific situations

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#439]
## Context/goal: 
I noticed some weird error is some situations while scanning vouchers.

## Task
- [ ] Reproduce all errors for these situations
- [ ] Create a list of all errors
- [ ] Improve errors textual
- [ ] Create tasks

**Comment by jamalv** [comment]
@GerbenBosschieter what do you think are the next steps? need any help with this?

**Comment by jamalv** [comment]
@jknnr is asking if we should get the list from @dev-rminds to know what errors there are

**Comment by GerbenBosschieter** [comment]
Close this issue. Most of the errors are now handled from backend and are aligned. Error handling is also added to test scenario's
