### ISSUE TITLE
Android: Switch records with profile

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#535]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/104476070-1c313200-55c0-11eb-8d39-512821ef102d.png)

Figma:
https://www.figma.com/file/zlpC5I10BP0M8sS5ueHor4/Me-Android?node-id=1127%3A0

## task
- [ ] navbar menu items profile will become eigenschappen
- [ ] add to eigenschappen and profile icon to open profile page
- [ ] add to vouchers a button to open profile page
