### ISSUE TITLE
Create a new Voucher info button

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#540]
## Context/goal: 
Discussed with stakeholder;
![image](https://user-images.githubusercontent.com/10818702/105332474-f2d26080-5bd4-11eb-8844-077701e2ef0e.png)

## Task
- [ ] Move option to open voucher to be a seperate button
- [ ] text should be 'Bekijk het aanbod'
- [ ] icon should be Material design icons: tag
https://iconify.design/icon-sets/mdi/tag.html
