### ISSUE TITLE
Text fix: change 'Scan deze QR-code' 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#542]
## Context/goal: 
<img height=400 src=https://user-images.githubusercontent.com/10818702/107345192-9cfe2380-6ac3-11eb-9a16-2ad1c28737b6.png>

## Task
- [x] add strings to strings.xml
- [x] title is the variable 'Record_type_translation' example: 'E-mailadres' or 'Naam'
- [x] subtitle is "Dit is uw eigenschap in de vorm van een QR-code. Laat de beoordelaar deze code scannen.
